name: "Publish Action"
on: create

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Publishing  Action
        uses: technote-space/release-github-actions@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_NAME: ngx-uptodate[bot]
          COMMIT_EMAIL: ngx-uptodate@users.noreply.github.com
          COMMIT_MESSAGE: "chore(realease): publishing new version from '${{github.ref}}'"
          CREATE_MAJOR_VERSION_TAG: true
          CREATE_MINOR_VERSION_TAG: true
          CREATE_PATCH_VERSION_TAG: true
          OUTPUT_BUILD_INFO_FILENAME: build.json
          BRANCH_NAME: releases
          CLEAN_TARGETS: ".[!.]*,__tests__,assets,demo,src,utility,*.js,*.ts,*.json,*.lock,_config.yml"
          TEST_TAG_PREFIX: test/
