name: "Test JavaScript Action"
on:
  pull_request:
  push:
    branches:    
      - develop
      - 'releases/*'   # only run in release distribution branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing NPM modules
        run: npm ci

      - name: Building action
        run: npm run build

      - name: Running tests
        run: npm test
      - uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
